### ISSUE TITLE
small changes

### ISSUE THREAD

**Issue by hyphop** [free-electrons/cedrus-frame-test#1]
plz check my small patch which make some small correction 

https://github.com/hyphop/v4l2-request-test/commit/256f893ddca06eeaf164cbe0eed1aee47dd368de

**Comment by paulkocialkowski** [comment]
Hi and thanks for the fix! I guess the proper procedure here would be to make a pull request.
But before you do that, please give the fix a proper commit message and avoid printing the fd on error condition (it doesn't provide any extra information). If you prefer, I could craft a commit with your fix myself too.

**Comment by hyphop** [comment]
hi u right ! i do another commit plz check it & read my comment bellow as commit message !
https://github.com/hyphop/v4l2-request-test/commit/0d9c7bcba15772ae2d98a2e34a1a803d605ecf56

**Comment by hyphop** [comment]
hi 
plz check new commit i think its more correct and read comment bellow as commit message !
https://github.com/hyphop/v4l2-request-test/commit/0d9c7bcba15772ae2d98a2e34a1a803d605ecf56

**Comment by hyphop** [comment]
i try to check hw video decode via cedrus from this manual https://linux-sunxi.org/Sunxi-cedrus
on my orange pi zero plus 2  device
i think im very close but something  wrong 
may be u can check and say somthing about my results https://gist.github.com/hyphop/922555b1e9d606cf08cb3b00524441b3

BIG TNX for work
