### ISSUE TITLE
undefined symbol: drmModeAddFB2WithModifiers

### ISSUE THREAD

**Issue by petit-miner** [free-electrons/cedrus-frame-test#17]
Hi there,
I have some issues using the request-test application. I probably did something wrong while linking the application or installed a library wrong. I think it is more of an issue with my building environment than the software itself. 
I'm using the Linux Cedrus Kernel (release-2019.03) and the matching kernel headers exported from the source to /usr. Also libva-v4l2-request and v4l2-request-test  with the same release tag.

`root@LicheePi:~/v4l2-request-test# ./v4l2-request-test -f 2 -l
Config:
 Video path: /dev/video0
 Media path: /dev/media0
 DRM path: /dev/dri/card0
 DRM driver: sun4i-drm
 Slices path: data/bbb-mpeg2
 Slices filename format: slice-%d.dump
 FPS: 2

Preset:
 Name: bbb-mpeg2
 Description: big_buck_bunny_480p_MPEG2_MP2_25fps_1800K.MPG
 License: Creative Commons Attribution 3.0
 Attribution: Blender Foundation | www.blender.org
 Width: 854
 Height: 480
 Frames count: 25
 Format: MPEG2

Media device driver: cedrus
Destination format: NV12 YUV
./v4l2-request-test: symbol lookup error: ./v4l2-request-test: undefined symbol: drmModeAddFB2WithModifiers`

**Comment by paulkocialkowski** [comment]
Hi! This indeed looks like an error with your setup, as drmModeAddFB2WithModifiers was likely available at build time but no longer at runtime. This is part of libdrm, so you might want to check what you have available with your setup. Closing since this is not directly due to the tool.
