### ISSUE TITLE
fix incorrect check block for opening media node

### ISSUE THREAD

**Issue by hyphop** [free-electrons/cedrus-frame-test#2]
fix incorrect check block for opening media node ( original block just
copied from prev lines for video node, and forget change video/media )

https://github.com/hyphop/v4l2-request-test/commit/65d6cf795a2a28932ff26851f2bfa9bd761077e0

**Comment by hyphop** [comment]
) have seen last patch but u still forget fix it

**Comment by paulkocialkowski** [comment]
Sorry for the delay! Could you rework the commit message like this:

> Fix incorrect check block for opening media node
>
> Original block just copied from prev lines for video node, and forget to change video/media.

So that the subject and description are not on a single line. Also, we need your signed-off-by line before merging the patch, see: https://developercertificate.org/

You can add it with:
> git commit --amend -s

Thanks!
