### ISSUE TITLE
Unable to find any connected connector

### ISSUE THREAD

**Issue by petit-miner** [free-electrons/cedrus-frame-test#4]
Hi there,

I'm struggling to test the VPU of the V3s. The display-engine and sun4i-drm are enabled in the devicetree:

[    1.729904] sun4i-drm display-engine: bound 1100000.mixer (ops 0xc094947c)
[    1.737527] sun4i-drm display-engine: bound 1c0c000.lcd-controller (ops 0xc0946160)
[    1.745296] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    1.751916] [drm] No driver support for vblank timestamp query.
[    1.758633] [drm] Initialized sun4i-drm 1.0.0 20150629 for display-engine on minor 0
[    1.767556] [drm] Cannot find any crtc or sizes

When I try to run v4l2-request-test:

root@LicheePi:~/v4l2-request-test# ./v4l2-request-test -f 25 -l
Config:
 Video path: /dev/video0
 Media path: /dev/media0
 DRM path: /dev/dri/card0
 DRM driver: sun4i-drm
 Slices path: data/bbb-mpeg2
 Slices filename format: slice-%d.dump
 FPS: 25

Preset:
 Name: bbb-mpeg2
 Description: big_buck_bunny_480p_MPEG2_MP2_25fps_1800K.MPG
 License: Creative Commons Attribution 3.0
 Attribution: Blender Foundation | www.blender.org
 Width: 854
 Height: 480
 Frames count: 25
 Format: MPEG2

Media device driver: cedrus
Destination format: NV12 YUV
Unable to find any connected connector
Unable to select DRM connector/encoder
Unable to start display engine

I'm currently working with the mainline 5.0 kernel. Should I use the Linux Media tree?

thanks

**Comment by paulkocialkowski** [comment]
Hey!

It looks like the issue you're having is on the DRM driver side:
> [drm] Cannot find any crtc or sizes

Indicates that you don't have a working display pipeline with the DRM driver. As a result, our tool doesn't find any connected connector and can't output anything.

Do you have a screen connected to your board at all and does it work properly with e.g. fbcon?

**Comment by petit-miner** [comment]
Yes I connected a parallel LCD and I can see the terminal, however my inital plan was to use the VPU to take video input from a parallel camera and decode it to h264. Is there userspace software out there, that supports this? (like ffmpeg?) Or is this WIP?  

thanks
